defaults:
  - _self_
  - data: data_loader
  - model: black_karasinski
  - solver: euler_maruyama

sim:
  run_func:
    _target_: simulation.simulation
  bond: 240
  save_plots: False
  forecast: 6/8/2024